export default [
        
[
    {
        title:'第1章 数据结构概述',
        url:'http://data.biancheng.net/view/0.html'
    },{
        title:'1.什么是数据结构',
        url:'http://data.biancheng.net/view/153.html'
    },{
        title:'2.数据结构到底学什么？',
        url:'http://data.biancheng.net/view/154.html'
    },{
        title:'3.数据的逻辑结构和物理结构',
        url:'http://data.biancheng.net/view/155.html'
    },{
        title:'4.如何衡量一个算法的好坏？',
        url:'http://data.biancheng.net/view/156.html'
    },{
        title:'5.数据结构和算法的关系和区别',
        url:'http://data.biancheng.net/view/157.html'
    },{
        title:'6.数据结构如何自学，效率更高？',
        url:'http://data.biancheng.net/view/158.html'
    },{
        title:'7.数学不好，对学数据结构有影响吗？',
        url:'http://data.biancheng.net/view/159.html'
    },{
        title:'8.学好数据结构，你已然超越了99%的程序员！',
        url:'http://data.biancheng.net/view/160.html'
    }
],
[
    {
        title:'第2章 线性表',
        url:'http://data.biancheng.net/view/0.html'
    },{
        title:'1.什么是线性表',
        url:'http://data.biancheng.net/view/157.html'
    },{
        title:'2.顺序表是什么',
        url:'http://data.biancheng.net/view/158.html'
    },{
        title:'3.顺序表的基本操作',
        url:'http://data.biancheng.net/view/159.html'
    },{
        title:'4.链表是什么',
        url:'http://data.biancheng.net/view/160.html'
    },{
        title:'5.链表的基本操作',
        url:'http://data.biancheng.net/view/161.html'
    },{
        title:'6.顺序表和链表有哪些不同？',
        url:'http://data.biancheng.net/view/162.html'
    },{
        title:'7.存储结构和存取结构，完全不是一码事！',
        url:'http://data.biancheng.net/view/163.html'
    },{
        title:'8.4种算法，实现单链表的反转！',
        url:'http://data.biancheng.net/view/164.html'
    },{
        title:'9.如何判断两个单链表相交？',
        url:'http://data.biancheng.net/view/165.html'
    },{
        title:'10.静态链表：更高级的线性表',
        url:'http://data.biancheng.net/view/166.html'
    },{
        title:'11.静态链表基本操作',
        url:'http://data.biancheng.net/view/167.html'
    },{
        title:'12.静态链表和动态链表区别',
        url:'http://data.biancheng.net/view/168.html'
    },{
        title:'13.循环链表实现约瑟夫环',
        url:'http://data.biancheng.net/view/169.html'
    },{
        title:'14.如何判断链表中有环？',
        url:'http://data.biancheng.net/view/170.html'
    },{
        title:'15.双向链表是什么',
        url:'http://data.biancheng.net/view/171.html'
    },{
        title:'16.双向链表的基本操作',
        url:'http://data.biancheng.net/view/172.html'
    },{
        title:'17.双向链表实现贪吃蛇游戏（含源码）',
        url:'http://data.biancheng.net/view/173.html'
    },{
        title:'18.双向循环链表（C语言）',
        url:'http://data.biancheng.net/view/174.html'
    },{
        title:'19.[项目实践]俄罗斯轮盘赌小游戏',
        url:'http://data.biancheng.net/view/175.html'
    }
],
[
    {
        title:'第3章 栈和队列',
        url:'http://data.biancheng.net/view/0.html'
    },{
        title:'1.什么是栈',
        url:'http://data.biancheng.net/view/169.html'
    },{
        title:'2.顺序栈的基本操作',
        url:'http://data.biancheng.net/view/170.html'
    },{
        title:'3.链栈的基本操作',
        url:'http://data.biancheng.net/view/171.html'
    },{
        title:'4.[项目实践]进制转换器',
        url:'http://data.biancheng.net/view/172.html'
    },{
        title:'5.[项目实践]括号匹配',
        url:'http://data.biancheng.net/view/173.html'
    },{
        title:'6.如何用栈实现求表达式的值？',
        url:'http://data.biancheng.net/view/174.html'
    },{
        title:'7.什么是队列',
        url:'http://data.biancheng.net/view/175.html'
    },{
        title:'8.顺序队列及其实现',
        url:'http://data.biancheng.net/view/176.html'
    },{
        title:'9.链式队列及基本操作',
        url:'http://data.biancheng.net/view/177.html'
    },{
        title:'10.为什么说栈和队列是线性存储结构？',
        url:'http://data.biancheng.net/view/178.html'
    },{
        title:'11.[项目实践]变态的停车场管理系统',
        url:'http://data.biancheng.net/view/179.html'
    },{
        title:'12.[项目实践]扑克牌小游戏',
        url:'http://data.biancheng.net/view/180.html'
    }
],
[
    {
        title:'第4章 字符串',
        url:'http://data.biancheng.net/view/0.html'
    },{
        title:'1.什么是串存储结构',
        url:'http://data.biancheng.net/view/175.html'
    },{
        title:'2.串的定长顺序存储',
        url:'http://data.biancheng.net/view/176.html'
    },{
        title:'3.串的堆分配存储',
        url:'http://data.biancheng.net/view/177.html'
    },{
        title:'4.串的块链存储',
        url:'http://data.biancheng.net/view/178.html'
    },{
        title:'5.BF算法（串模式匹配算法）',
        url:'http://data.biancheng.net/view/179.html'
    },{
        title:'6.KMP算法',
        url:'http://data.biancheng.net/view/180.html'
    },{
        title:'7.[项目实践]字符过滤系统',
        url:'http://data.biancheng.net/view/181.html'
    }
],
[
    {
        title:'第5章 数组和广义表',
        url:'http://data.biancheng.net/view/0.html'
    },{
        title:'1.什么是数组',
        url:'http://data.biancheng.net/view/181.html'
    },{
        title:'2.数组的顺序存储',
        url:'http://data.biancheng.net/view/182.html'
    },{
        title:'3.矩阵（稀疏矩阵）压缩存储',
        url:'http://data.biancheng.net/view/183.html'
    },{
        title:'4.三元组顺序表',
        url:'http://data.biancheng.net/view/184.html'
    },{
        title:'5.行逻辑链接的顺序表',
        url:'http://data.biancheng.net/view/185.html'
    },{
        title:'6.十字链表法',
        url:'http://data.biancheng.net/view/186.html'
    },{
        title:'7.矩阵的转置算法',
        url:'http://data.biancheng.net/view/187.html'
    },{
        title:'8.稀疏矩阵的快速转置',
        url:'http://data.biancheng.net/view/188.html'
    },{
        title:'9.矩阵乘法（基于行逻辑链接的顺序表）',
        url:'http://data.biancheng.net/view/189.html'
    },{
        title:'10.矩阵加法（基于十字链表）',
        url:'http://data.biancheng.net/view/190.html'
    },{
        title:'11.什么是广义表',
        url:'http://data.biancheng.net/view/191.html'
    },{
        title:'12.广义表的存储结构',
        url:'http://data.biancheng.net/view/192.html'
    },{
        title:'13.广义表的深度和长度',
        url:'http://data.biancheng.net/view/193.html'
    },{
        title:'14.复制广义表',
        url:'http://data.biancheng.net/view/194.html'
    }
],
[
    {
        title:'第6章 树',
        url:'http://data.biancheng.net/view/0.html'
    },{
        title:'1.树的存储结构',
        url:'http://data.biancheng.net/view/23.html'
    },{
        title:'2.什么是二叉树',
        url:'http://data.biancheng.net/view/24.html'
    },{
        title:'3.二叉树的顺序存储结构',
        url:'http://data.biancheng.net/view/25.html'
    },{
        title:'4.二叉树的链式存储结构',
        url:'http://data.biancheng.net/view/26.html'
    },{
        title:'5.浅谈二叉树的（4种）遍历算法',
        url:'http://data.biancheng.net/view/27.html'
    },{
        title:'6.二叉树先序遍历（递归与非递归）',
        url:'http://data.biancheng.net/view/28.html'
    },{
        title:'7.二叉树中序遍历（递归和非递归）',
        url:'http://data.biancheng.net/view/29.html'
    },{
        title:'8.二叉树后序遍历（递归与非递归）',
        url:'http://data.biancheng.net/view/30.html'
    },{
        title:'9.二叉树层次遍历',
        url:'http://data.biancheng.net/view/31.html'
    },{
        title:'10.线索二叉树(C语言实现)',
        url:'http://data.biancheng.net/view/32.html'
    },{
        title:'11.双向线索二叉树的建立',
        url:'http://data.biancheng.net/view/33.html'
    },{
        title:'12.树的双亲表示法',
        url:'http://data.biancheng.net/view/34.html'
    },{
        title:'13.树的孩子表示法',
        url:'http://data.biancheng.net/view/35.html'
    },{
        title:'14.树的孩子兄弟表示法',
        url:'http://data.biancheng.net/view/36.html'
    },{
        title:'15.森林转化为二叉树',
        url:'http://data.biancheng.net/view/37.html'
    },{
        title:'16.哈夫曼树',
        url:'http://data.biancheng.net/view/38.html'
    },{
        title:'17.回溯算法',
        url:'http://data.biancheng.net/view/39.html'
    },{
        title:'18.n个结点的二叉树种类',
        url:'http://data.biancheng.net/view/40.html'
    },{
        title:'19.[项目实践]移动迷宫小游戏(初级版)',
        url:'http://data.biancheng.net/view/41.html'
    }
],
[
    {
        title:'第7章 图',
        url:'http://data.biancheng.net/view/0.html'
    },{
        title:'1.什么是图存储结构',
        url:'http://data.biancheng.net/view/200.html'
    },{
        title:'2.什么是连通图',
        url:'http://data.biancheng.net/view/201.html'
    },{
        title:'3.什么是生成树',
        url:'http://data.biancheng.net/view/202.html'
    },{
        title:'4.图的顺序存储结构',
        url:'http://data.biancheng.net/view/203.html'
    },{
        title:'5.图的邻接表存储法',
        url:'http://data.biancheng.net/view/204.html'
    },{
        title:'6.图的十字链表存储法',
        url:'http://data.biancheng.net/view/205.html'
    },{
        title:'7.图的邻接多重表存储法',
        url:'http://data.biancheng.net/view/206.html'
    },{
        title:'8.深度优先搜索和广度优先搜索',
        url:'http://data.biancheng.net/view/207.html'
    },{
        title:'9.深度优先生成树和广度优先生成树',
        url:'http://data.biancheng.net/view/208.html'
    },{
        title:'10.普里姆算法(Prim算法)',
        url:'http://data.biancheng.net/view/209.html'
    },{
        title:'11.克鲁斯卡尔算法(Kruskal算法)',
        url:'http://data.biancheng.net/view/210.html'
    },{
        title:'12.重连通图',
        url:'http://data.biancheng.net/view/211.html'
    },{
        title:'13.拓扑排序算法',
        url:'http://data.biancheng.net/view/212.html'
    },{
        title:'14.关键路径',
        url:'http://data.biancheng.net/view/213.html'
    },{
        title:'15.迪杰斯特拉算法',
        url:'http://data.biancheng.net/view/214.html'
    },{
        title:'16.弗洛伊德算法',
        url:'http://data.biancheng.net/view/215.html'
    },{
        title:'17.[项目实践]移动迷宫小游戏(升级版)',
        url:'http://data.biancheng.net/view/216.html'
    }
],
[
    {
        title:'第8章 动态内存管理',
        url:'http://data.biancheng.net/view/0.html'
    },{
        title:'1.动态内存管理',
        url:'http://data.biancheng.net/view/48.html'
    },{
        title:'2.边界标识法',
        url:'http://data.biancheng.net/view/49.html'
    },{
        title:'3.伙伴系统',
        url:'http://data.biancheng.net/view/50.html'
    },{
        title:'4.系统垃圾回收机制',
        url:'http://data.biancheng.net/view/51.html'
    },{
        title:'5.内存紧缩（内存碎片化处理）',
        url:'http://data.biancheng.net/view/52.html'
    }
],
[
    {
        title:'第9章 查找算法',
        url:'http://data.biancheng.net/view/0.html'
    },{
        title:'1.什么是查找表',
        url:'http://data.biancheng.net/view/53.html'
    },{
        title:'2.顺序查找算法',
        url:'http://data.biancheng.net/view/54.html'
    },{
        title:'3.折半查找（二分查找）',
        url:'http://data.biancheng.net/view/55.html'
    },{
        title:'4.分块查找算法（索引顺序查找）',
        url:'http://data.biancheng.net/view/56.html'
    },{
        title:'5.静态树表查找算法',
        url:'http://data.biancheng.net/view/57.html'
    },{
        title:'6.二叉排序树（二叉查找树）',
        url:'http://data.biancheng.net/view/58.html'
    },{
        title:'7.平衡二叉树（AVL树）',
        url:'http://data.biancheng.net/view/59.html'
    },{
        title:'8.红黑树算法(更高级的二叉查找树)',
        url:'http://data.biancheng.net/view/60.html'
    },{
        title:'9.B-树及其基本操作',
        url:'http://data.biancheng.net/view/61.html'
    },{
        title:'10.B+树及插入和删除操作',
        url:'http://data.biancheng.net/view/62.html'
    },{
        title:'11.键树查找法（双链树和字典树）',
        url:'http://data.biancheng.net/view/63.html'
    },{
        title:'12.什么是哈希表（散列表）',
        url:'http://data.biancheng.net/view/64.html'
    },{
        title:'13.哈希查找算法',
        url:'http://data.biancheng.net/view/65.html'
    }
],
[
    {
        title:'第10章 排序算法',
        url:'http://data.biancheng.net/view/0.html'
    },{
        title:'1.插入排序算法',
        url:'http://data.biancheng.net/view/65.html'
    },{
        title:'2.折半插入排序算法',
        url:'http://data.biancheng.net/view/66.html'
    },{
        title:'3.2-路插入排序算法',
        url:'http://data.biancheng.net/view/67.html'
    },{
        title:'4.表插入排序算法',
        url:'http://data.biancheng.net/view/68.html'
    },{
        title:'5.希尔排序算法',
        url:'http://data.biancheng.net/view/69.html'
    },{
        title:'6.冒泡排序算法',
        url:'http://data.biancheng.net/view/70.html'
    },{
        title:'7.快速排序算法（QSort，快排）',
        url:'http://data.biancheng.net/view/71.html'
    },{
        title:'8.选择排序算法',
        url:'http://data.biancheng.net/view/72.html'
    },{
        title:'9.归并排序算法',
        url:'http://data.biancheng.net/view/73.html'
    },{
        title:'10.基数排序',
        url:'http://data.biancheng.net/view/74.html'
    },{
        title:'11.内部排序算法优势分析',
        url:'http://data.biancheng.net/view/75.html'
    }
],
[
    {
        title:'第11章 外部排序算法',
        url:'http://data.biancheng.net/view/0.html'
    },{
        title:'1.什么是外部排序算法',
        url:'http://data.biancheng.net/view/76.html'
    },{
        title:'2.多路平衡归并排序算法',
        url:'http://data.biancheng.net/view/77.html'
    },{
        title:'3.置换选择排序算法',
        url:'http://data.biancheng.net/view/78.html'
    },{
        title:'4.最佳归并树',
        url:'http://data.biancheng.net/view/79.html'
    }
],
[
    {
        title:'第12章 数据结构与算法视频教程',
        url:'http://data.biancheng.net/view/0.html'
    },{
        title:'1.小甲鱼数据结构与算法视频教程（98讲全）',
        url:'http://data.biancheng.net/view/206.html'
    },{
        title:'2.郝斌数据结构与算法视频教程',
        url:'http://data.biancheng.net/view/207.html'
    },{
        title:'3.国嵌数据结构与算法视频教程',
        url:'http://data.biancheng.net/view/208.html'
    },{
        title:'4.上海交大数据结构与算法视频教程',
        url:'http://data.biancheng.net/view/209.html'
    },{
        title:'5.吉林大学数据结构视频教程',
        url:'http://data.biancheng.net/view/210.html'
    },{
        title:'6.严蔚敏数据结构视频教程',
        url:'http://data.biancheng.net/view/211.html'
    }
]
]